In [1]:
import pandas as pd
import numpy as np

In [9]:
df_movie=pd.read_csv('Recommend.csv', header=None, names=['User_Id','Movie_Id','Rating','Timestap'])

In [10]:
df_movie.head()

User_Id  Movie_Id  Rating   Timestap
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [11]:
from sklearn. model_selection import train_test_split
n_users=df_movie.User_Id.unique().shape[0]
n_movies=df_movie.Movie_Id.unique().shape[0]

train_data, test_data=train_test_split(df_movie,test_size=0.25)


In [13]:
train_data_matrix=np.zeros((n_users,n_movies))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1]=line[3]
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [15]:
test_data_matrix=np.zeros((n_users,n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1]=line[3]
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
from sklearn.metrics import pairwise_distances
user_similar=pairwise_distances(train_data_matrix, metric='cosine')
movie_similar=pairwise_distances(train_data_matrix.T, metric='cosine')
mean_user=train_data_matrix.mean(axis=1)[:,np.newaxis]
ratings_differ= (train_data_matrix-mean_user)
user_pred=mean_user+user_similar.dot(ratings_differ)/np.array([np.abs(user_similar).sum(axis=1)]).T

user_pred

array([[ 1.60385854e+00,  5.65158194e-01,  4.78955183e-01, ...,
         3.05060062e-01,  3.07695349e-01,  3.07190413e-01],
       [ 1.32518272e+00,  2.65301279e-01,  1.31792183e-01, ...,
        -6.27939286e-02, -5.96238389e-02, -5.93974574e-02],
       [ 1.35335896e+00,  2.26891752e-01,  1.07143174e-01, ...,
        -9.63731746e-02, -9.30850842e-02, -9.29913893e-02],
       ...,
       [ 1.19861635e+00,  1.84459312e-01,  6.14289964e-02, ...,
        -1.29519731e-01, -1.26378738e-01, -1.26364346e-01],
       [ 1.38771883e+00,  2.98807428e-01,  1.95757435e-01, ...,
        -2.56702385e-03,  3.39122895e-04,  5.24109331e-04],
       [ 1.40928400e+00,  3.36001429e-01,  2.58566579e-01, ...,
         7.95294683e-02,  8.20515013e-02,  8.19696990e-02]])